# Generated by Django 4.0.3 on 2023-06-07 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_remove_user_verification_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='verification_method',
            field=models.CharField(choices=[('sms', 'SMS')], default=1, max_length=10),
            preserve_default=False,
        ),
    ]
