# Generated by Django 4.0.3 on 2023-06-07 11:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_user_verification_method'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='verification_method',
        ),
    ]
