# Generated by Django 4.0.3 on 2023-06-08 05:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0011_userprofile_email_userprofile_first_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='email',
        ),
    ]
