# Generated by Django 4.2 on 2023-06-08 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0013_userprofile_email"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="email",
            field=models.EmailField(default="", max_length=100),
        ),
    ]
