# Generated by Django 4.2 on 2023-06-09 07:12

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0014_alter_userprofile_email"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="created_date",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="user",
            name="date_joined",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="user",
            name="modified_date",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
