# Generated by Django 4.2 on 2023-06-09 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0015_user_created_date_user_date_joined_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="citizenship_back",
            field=models.ImageField(
                blank=True, null=True, upload_to="users/citicenship_photo"
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="citizenship_front",
            field=models.ImageField(
                blank=True, null=True, upload_to="users/citicenship_photo"
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="passport_photo",
            field=models.ImageField(
                blank=True, null=True, upload_to="users/passport_photo"
            ),
        ),
    ]
