# Generated by Django 4.2 on 2023-06-12 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0016_userprofile_citizenship_back_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="is_approved",
            field=models.BooleanField(default=False),
        ),
    ]
