# Generated by Django 4.2 on 2023-06-12 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0018_remove_user_is_approved"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="is_verified",
            field=models.BooleanField(default=False),
        ),
    ]
