# Generated by Django 4.2 on 2023-06-13 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0019_user_is_verified"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="tole_no",
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
