# Generated by Django 4.2 on 2023-06-13 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0020_userprofile_tole_no"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.PositiveSmallIntegerField(
                blank=True, choices=[(1, "Farmer"), (2, "Investor")], null=True
            ),
        ),
    ]
