# Generated by Django 4.2 on 2023-06-15 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0023_userprofile_facebook_userprofile_instagram_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="user_name",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
