# Generated by Django 4.0.3 on 2023-07-19 10:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0026_alter_notification_sender'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Notification',
        ),
    ]
