# Generated by Django 4.2.1 on 2023-05-27 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='verification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pidx', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name': 'verification',
                'verbose_name_plural': 'verification',
            },
        ),
        migrations.AddField(
            model_name='payment',
            name='pidx',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(choices=[('PayPal', 'PayPal'), ('Khalti', 'Khalti')], max_length=100),
        ),
    ]
