# Generated by Django 4.2.1 on 2023-05-27 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_verification_payment_pidx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='payment_status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('details', models.JSONField()),
            ],
        ),
        migrations.DeleteModel(
            name='verification',
        ),
    ]
