# Generated by Django 4.2 on 2023-06-12 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0004_remove_payment_amount_remove_payment_created_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="farmorder",
            name="reservation_expiration",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
