# Generated by Django 4.2 on 2023-06-13 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0005_farmorder_reservation_expiration"),
    ]

    operations = [
        migrations.DeleteModel(
            name="payment_status",
        ),
        migrations.AddField(
            model_name="payment",
            name="payment_status",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
