# Generated by Django 4.2 on 2023-06-14 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0006_delete_payment_status_payment_payment_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="total_data",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
