# Generated by Django 4.0.3 on 2023-06-28 08:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0038_project_is_soldout_alter_projectstatus_title'),
        ('orders', '0010_farmorder_vendors'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ecom.project'),
        ),
    ]
