# Generated by Django 4.0.3 on 2023-06-28 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0011_farmorder_return_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farmorder',
            name='return_amount',
            field=models.FloatField(default=0),
        ),
    ]
