# Generated by Django 4.0.3 on 2023-06-29 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0011_order_project'),
        ('orders', '0012_alter_farmorder_return_amount'),
    ]

    operations = [
    ]
