# Generated by Django 4.2.1 on 2023-05-16 05:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0003_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_title', models.CharField(max_length=50)),
                ('project_description', models.TextField(max_length=500)),
                ('duration_in_months', models.PositiveIntegerField()),
                ('total_cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('value_of_share', models.DecimalField(decimal_places=2, max_digits=10)),
                ('max_shares_per_user', models.PositiveIntegerField()),
                ('return_date', models.DateField()),
                ('percent_return_after_due_date', models.DecimalField(decimal_places=2, max_digits=5)),
                ('project_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecom.category')),
            ],
            options={
                'verbose_name': 'project',
                'verbose_name_plural': 'projects',
            },
        ),
    ]
