# Generated by Django 4.2.1 on 2023-05-16 05:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0005_project_created_at_project_farm_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='project',
            name='farm_image',
        ),
        migrations.RemoveField(
            model_name='project',
            name='updated_at',
        ),
    ]
