# Generated by Django 4.2.1 on 2023-05-16 05:34

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('vendor', '0002_remove_vendor_vendor_slug'),
        ('ecom', '0006_remove_project_created_at_remove_project_farm_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='project',
            name='farm_image',
            field=models.ImageField(blank=True, default='', upload_to='farmimages'),
        ),
        migrations.AddField(
            model_name='project',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='project',
            name='vendor',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, to='vendor.vendor'),
        ),
    ]
