# Generated by Django 4.2.1 on 2023-05-16 05:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_remove_userprofile_district_and_more'),
        ('ecom', '0007_project_created_at_project_farm_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='vendor',
        ),
        migrations.AddField(
            model_name='project',
            name='user_profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='account.userprofile'),
        ),
    ]
