# Generated by Django 4.2.1 on 2023-05-16 05:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_remove_userprofile_district_and_more'),
        ('ecom', '0008_remove_project_vendor_project_user_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='user_profile',
        ),
        migrations.AddField(
            model_name='project',
            name='vendor',
            field=models.ForeignKey(default='', limit_choices_to={'user__role': 1}, on_delete=django.db.models.deletion.CASCADE, to='account.userprofile'),
        ),
    ]
