# Generated by Django 4.2.1 on 2023-05-16 05:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_remove_userprofile_district_and_more'),
        ('ecom', '0010_alter_project_vendor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='vendor',
            field=models.ForeignKey(default='', limit_choices_to={'user__role': 1}, on_delete=django.db.models.deletion.CASCADE, to='account.userprofile'),
        ),
    ]
