# Generated by Django 4.2.1 on 2023-05-16 06:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_remove_userprofile_district_and_more'),
        ('ecom', '0012_remove_project_vendor_project_user_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='user_profile',
            field=models.ForeignKey(blank=True, default='', limit_choices_to={'user__role': 1}, null=True, on_delete=django.db.models.deletion.CASCADE, to='account.userprofile'),
        ),
    ]
