# Generated by Django 4.2.1 on 2023-05-16 08:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0015_remove_project_user_profile_project_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='email',
            new_name='user',
        ),
    ]
