# Generated by Django 4.2.1 on 2023-05-16 08:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ecom', '0017_remove_project_user_project_user_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='user_profile',
        ),
        migrations.AddField(
            model_name='project',
            name='vendor',
            field=models.ForeignKey(default=1, limit_choices_to={'role': 1}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='project',
            name='project_title',
            field=models.CharField(max_length=100),
        ),
    ]
