# Generated by Django 4.2.1 on 2023-05-16 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0018_remove_project_user_profile_project_vendor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='farm_image',
            field=models.ImageField(blank=True, default='', upload_to='media/farmimages/'),
        ),
    ]
