# Generated by Django 4.2.1 on 2023-05-21 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0022_alter_project_vendor'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='descrption_title',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
