# Generated by Django 4.2 on 2023-06-08 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ecom", "0025_tax"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="is_approved",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="project",
            name="is_available",
            field=models.BooleanField(default=True),
        ),
    ]
