# Generated by Django 4.2 on 2023-06-11 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ecom", "0026_project_is_approved_project_is_available"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="total_no_shares",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
