# Generated by Django 4.2 on 2023-06-15 08:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ecom", "0028_extraimage"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="project",
            name="duration_in_months",
        ),
    ]
