# Generated by Django 4.0.3 on 2023-06-18 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0029_remove_project_duration_in_months'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='total_no_shares',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=10),
        ),
    ]
