# Generated by Django 4.0.3 on 2023-06-18 11:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ecom', '0030_alter_project_total_no_shares'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompletedProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_title', models.CharField(max_length=100)),
                ('project_description', models.TextField(max_length=500)),
                ('total_cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_no_shares', models.DecimalField(decimal_places=0, max_digits=10)),
                ('value_of_share', models.DecimalField(decimal_places=2, max_digits=10)),
                ('max_shares_per_user', models.PositiveIntegerField()),
                ('return_date', models.DateField()),
                ('percent_return_after_due_date', models.DecimalField(decimal_places=2, max_digits=5)),
                ('farm_image', models.ImageField(blank=True, default='', upload_to='media/farmimages/')),
                ('description_title', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('completed_at', models.DateTimeField(auto_now_add=True)),
                ('project_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecom.category')),
                ('vendor', models.ForeignKey(limit_choices_to={'role': 1}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
