# Generated by Django 4.0.3 on 2023-06-19 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0033_project_is_completed'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CompletedProject',
        ),
    ]
