# Generated by Django 4.0.3 on 2023-06-20 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0034_delete_completedproject'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='collected_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='project',
            name='descrption_title',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
