# Generated by Django 4.0.3 on 2023-06-25 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0037_projectstatus_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='is_soldout',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='projectstatus',
            name='title',
            field=models.CharField(blank=True, default='Status Update', max_length=100, null=True),
        ),
    ]
