# Generated by Django 4.0.3 on 2023-06-29 06:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0038_project_is_soldout_alter_projectstatus_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='project',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='ecom.project'),
        ),
    ]
