# Generated by Django 4.0.3 on 2023-06-29 06:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ecom', '0039_alter_cart_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecom.project'),
        ),
        migrations.AlterField(
            model_name='cart',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
