# Generated by Django 4.0.3 on 2023-06-29 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0039_remove_project_descrption_title_and_more'),
        ('ecom', '0040_alter_cart_project_alter_cart_user'),
    ]

    operations = [
    ]
