# Generated by Django 4.0.3 on 2023-07-06 09:19

import django.core.validators
from django.db import migrations, models
import ecom.models


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0043_alter_project_project_documents'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='project_documents',
            field=models.FileField(blank=True, null=True, upload_to='media/Project/documents/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'doc', 'docx']), ecom.models.validate_file_extension]),
        ),
    ]
