# Generated by Django 4.0.3 on 2023-07-09 08:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0045_category_vendor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='vendor',
        ),
    ]
