# Generated by Django 4.0.3 on 2023-07-11 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0048_remove_project_address_remove_project_city_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
