# Generated by Django 4.0.3 on 2023-07-18 07:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0045_venue'),
        ('ecom', '0050_alter_project_latitude_alter_project_longitude'),
    ]

    operations = [
    ]
