# Generated by Django 4.0.3 on 2023-07-14 07:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0051_merge_20230712_2157'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Venue',
        ),
    ]
