# Generated by Django 4.0.3 on 2023-07-19 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0051_notice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notice',
            name='notice',
            field=models.TextField(max_length=2000),
        ),
    ]
